[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
game = {path = "../game"}
movegen = {path = "../movegen"}
rocket = {version = "0.5.1", features = ["json"]}
